name: Build RIPE Atlas Software Probe
on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  debian:
    runs-on: ubuntu-24.04
    steps:
    - name: "Set up Lima"
      uses: lima-vm/lima-actions/setup@v1
      id: lima-actions-setup

    - name: "Cache ~/.cache/lima"
      uses: actions/cache@v4
      with:
        path: ~/.cache/lima
        key: lima-${{ steps.lima-actions-setup.outputs.version }}

    - name: "Start a Debian 12 VM"
      run: |
        limactl start --name=default --cpus=1 --memory=1 --network=lima:user-v2 --mount-writable --mount-type=virtiofs template://debian-12

    - name: "BUILD.md"
      run: |
        set -eux
        # Building dependencies
        lima pwd
        lima ls
        lima sudo apt-get update
        lima sudo apt-get -y install git build-essential debhelper libssl-dev autotools-dev psmisc net-tools systemd
        lima git clone --depth 1 -b "${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}" "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
        lima pushd ripe-atlas-software-probe
        lima pwd
        lima ls

        # Building the packages
        lima dpkg-buildpackage -b -us -uc
        lima cp ../ripe-atlas-*.deb .
        lima pushd .repo
        lima dpkg-buildpackage -b -us -uc
        lima popd

        # Installing the probe package
        lima sudo dpkg -i ripe-atlas-common*.deb ripe-atlas-probe*.deb
        lima pwd
        lima ls
        # Follow the instructions printed after installation to start and register and your probe
        lima popd